language: node_js
node_js:
  - "0.11"
  - "0.10"

before_install:
  - npm install -g gulp bower

install:
  - npm install
  - bower install
  - node_modules/gulp-jscs/node_modules/jscs/bin/jscs *.js test/*.js
  - node_modules/gulp-jshint/node_modules/jshint/bin/jshint *.js test/*.js
  - gulp --homepage
